services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=maylikenoother
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=openlicensemediadb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maylikenoother -d openlicensemediadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://maylikenoother:123456789@db:5432/openlicensemediadb
      - OPENVERSE_API_URL=https://api.openverse.engineering/v1/
      
      - CLERK_JWT_ISSUER=${CLERK_JWT_ISSUER}
      - CLERK_JWT_JWKS_URL=${CLERK_JWT_JWKS_URL}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data: