services:
  - type: web
    name: olm-search-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: CLERK_JWT_ISSUER
        sync: false
      - key: CLERK_JWT_JWKS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: OPENVERSE_API_URL
        value: https://api.openverse.engineering/v1/
      - key: ALLOWED_ORIGINS
        value: https://olm-search.onrender.com
      - key: FRONTEND_URL
        value: https://olm-search.onrender.com
 
  - type: web
    name: olm-search
    env: static
    buildCommand: cd frontend && chmod +x build.sh && ./build.sh
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_API_URL
        value: https://olm-search-backend.onrender.com/api
      - key: VITE_RENDER
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html