# render.yaml
services:
  # Backend service
  - type: web
    name: olm-search-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://maylikenoother1999:ogedengbe1999@cluster0.itt0evk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: CLERK_JWT_ISSUER
        sync: false
      - key: CLERK_JWT_JWKS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: OPENVERSE_API_URL
        value: https://api.openverse.engineering/v1/
      - key: ALLOWED_ORIGINS
        value: https://olm-search.onrender.com
      - key: FRONTEND_URL
        value: https://olm-search.onrender.com

  # Frontend service  
  - type: web
    name: olm-search
    env: static
    buildCommand: cd frontend && chmod +x build.sh && ./build.sh
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_API_URL
        value: https://olm-search-backend.onrender.com/api
      - key: VITE_RENDER
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # MongoDB service
  - type: pserv
    name: mongodb
    env: docker
    repo: https://github.com/render-examples/mongodb.git
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: openlicensemediadb
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 3